---
title: "exercise8 labwork"
author: "Gayane Hovsepyan"
date: "March 1, 2017"
output: html_document
---

## Exploring cocoli file

```{r}
cocoli_dat <- read.table("/home/eeb177-student/Desktop/eeb-177/class-assignments/classwork-21-Feb/cocoli.txt", header = TRUE)
head(cocoli_dat)
str(cocoli_dat)

View(cocoli_dat)

sizes_in_1994 <- cocoli_dat$dbh1
names(sizes_in_1994) <- cocoli_dat$tag
sizes_in_1994[1] # subset a vector by position
sizes_in_1994["000001"] # subset a vector by name

sizes_in_1997 <- cocoli_dat$dbh2
names(sizes_in_1997) <- cocooli_dat$tag

sizes_in_1998 <- cocoli_dat$dbh3
names(sizes_in_1998) <- cocooli_dat$tag

#find all instances of dbh = 171
sizes_in_1994 ==171

#we want to know the fate of all trees that began 1994 with dbh 171
trees_171_1994 = which(sizes_in_1994==171)
trees_171_1994

sizes_in_1994

#in the 1997 list, find these individuals that used to be eb 171 mm

sizes_in_1997[trees_171_1994]
## Calculate RGR between 1994=1997
#(size in 97 - size in 94) /size in 94

yearly_RGR = ((cocoli_dat$dbh2- cocoli_dat$dbh1)/cocoli_dat$dbh1)/3

#add the RGR column
cocoli_dat$rgr1 - yearly_RGR
View(cocoli_dat)

```

``` {r}
hist(cocoli_dat$dbh1, xlab= "DBH in 1994(mm)", "Distributions of sizes in 1994")

```

```{r}
library (ggplot2)
ggplot(cocoli_dat) + geom_histogram(aes(dbh1)) + geom_histogram(aes(dbh2)), fill = "red", alpha = 0.2)


gtitle("Distributions of sizes in '94")
```





