---
title: "Exercise-8-Introduction to R Graphics with ggplot2"
author: "Gayane Hovsepyan"
date: "March 1, 2017"
output: html_document
---

## Example Data: Housing Data
```{r}
housing <- read.csv("/home/eeb177-student/Desktop/eeb-177/lab-work/exercise-8/Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])
```

#Histograms

```{r}
hist(housing$Home.Value) # basic hsitogram
```

```{r}
library(ggplot2)
ggplot(housing, aes(x = Home.Value)) +
  geom_histogram() ## shape of overall histogram important
```
## Base graphics VS ggplot for more complex graphs:
```{r}
plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red",
       data=subset(housing, State == "TX"))
legend(1975, 400000,
       c("MA", "TX"), title="State",
       col=c("black", "red"),
       pch=c(1, 1)) #base color scatter plot
```
```{r}
ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point() #colored scatter plot
```
## Geometric Objects And Aesthetics
```{r}
help.search("geom_", package = "ggplot2")
```
```{r}
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = Land.Value)) +
  geom_point() # scatter plot 
```
```{r}
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = log(Land.Value))) +
  geom_point() #log x so that it's not so smushed
```
```{r}
  hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ Land.Value, data = hp2001Q1))

  p1 <- ggplot(hp2001Q1, aes(x = Land.Value, y = Structure.Cost))

  p1 + geom_point(aes(color = Home.Value)) +
    geom_line(aes(y = pred.SC))
```
```{r}
 p1 +
    geom_point(aes(color = Home.Value)) +
    geom_smooth()
```
```{r}
p1 + 
    geom_text(aes(label=State), size = 3)
```
```{r}
install.packages("ggrepel") 
  library("ggrepel")
  p1 + 
    geom_point() + 
    geom_text_repel(aes(label=State), size = 3)
```
```{r}

 p1 +
    geom_point(aes(size = 2),# incorrect! 2 is not a variable
               color="red") # this is fine -- all points red
```
```{r}
dat <- read.csv("dataSets/EconomistData.csv")
```
# Exercise 1
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point() #Create a scatter plot with CPI on the x axis and HDI on the y axis.
```
```{r}
 ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point(color = "blue") #Color the points in the previous plot blue
```
```{r}
 ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point(aes(color = Region)) #color according to region
```
```{r}
  ggplot(dat, aes(x = Region, y = CPI)) +
    geom_boxplot() # boxplots of cpi by region
```
```{r}
  ggplot(dat, aes(x = Region, y = CPI)) +
    geom_boxplot() +
    geom_point() #points on top of boxplots
```
## statistic transformations
```{r}
  args(geom_histogram)
  args(stat_bin)
```
```{r}
p2 <- ggplot(housing, aes(x = Home.Value))
  p2 + geom_histogram()
```
```{r}
p2 + geom_histogram(stat = "bin", binwidth=4000)
```
## Changing Statistic Transformations
```{r}
housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
  rbind(head(housing.sum), tail(housing.sum))
```
```{r}
  ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
    geom_bar()
```
```{r}
ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
    geom_bar(stat="identity")
```
## Exercise II
```{r}
  ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point() #Re-create a scatter plot with CPI on the x axis and HDI on the y axis (as you did in the previous exercise
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point() +
    geom_smooth(method = "lm") #Overlay a smoothing line on top of the scatter plot using the *lm* method

```
```{r}
 ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point() +
    geom_smooth() #Overlay a smoothing line on top of the scatter plot using the default method
```
```{r}
ggplot(dat, aes(x = CPI, y = HDI)) +
    geom_point() +
    geom_smooth(span = .4) #BONUS
```
## Scales
```{r}
 p3 <- ggplot(housing,
               aes(x = State,
                   y = Home.Price.Index)) + 
          theme(legend.position="top",
                axis.text=element_text(size = 6))
  (p4 <- p3 + geom_point(aes(color = Date),
                         alpha = 0.5,
                         size = 1.5,
                         position = position_jitter(width = 0.25, height = 0)))

```
```{r}
#Scale Modification Examples
 p4 + scale_x_discrete(name="State Abbreviation") +
    scale_color_continuous(name="",
                           breaks = c(19751, 19941, 20131),
                           labels = c(1971, 1994, 2013))

```
```{r}
p4 +
    scale_x_discrete(name="State Abbreviation") +
    scale_color_continuous(name="",
                           breaks = c(19751, 19941, 20131),
                           labels = c(1971, 1994, 2013),
                           low = "blue", high = "red")

```
```{r}
 p4 +
    scale_color_continuous(name="",
                           breaks = c(19751, 19941, 20131),
                           labels = c(1971, 1994, 2013),
                           low = muted("blue"), high = muted("red"))

```
```{r}
 p4 +
    scale_color_gradient2(name="",
                          breaks = c(19751, 19941, 20131),
                          labels = c(1971, 1994, 2013),
                          low = muted("blue"),
                          high = muted("red"),
                          mid = "gray60",
                          midpoint = 19941) #Using different color scales

```
## Exercise III
```{r}
 ggplot(dat, aes(x = CPI, y = HDI, color = "Region")) +
    geom_point() #Create a scatter plot with CPI on the x axis and HDI on the y axis. Color the points to indicate region.

```
```{r}
ggplot(dat, aes(x = CPI, y = HDI, color = "Region")) +
  geom_point() +
  scale_x_continuous(name = "Corruption Perception Index") +
  scale_y_continuous(name = "Human Development Index") +
  scale_color_discrete(name = "Region of the world") # Modify the x, y, and color scales so that they have more easily-understood names (e.g., spell out "Human development Index" instead of "HDI")

```
```{r}
ggplot(dat, aes(x = CPI, y = HDI, color = "Region")) +
  geom_point() +
  scale_x_continuous(name = "Corruption Perception Index") +
  scale_y_continuous(name = "Human Development Index") +
    scale_color_manual(name = "Region of the world",
                       values = c("#24576D",
                                  "#099DD7",
                                  "#28AADC",
                                  "#248E84",
                                  "#F2583F",
                                  "#96503F")) #Modify the color scale to use specific values of your choosing.

```
## Faceting
```{r}
 p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
  p5 + geom_line(aes(color = State)) # trend in housing prices, mapping state to color

```
```{r}
  (p5 <- p5 + geom_line() +
     facet_wrap(~State, ncol = 10)) # faceting by state

```
## Themes
```{r}
 p5 + theme_linedraw()

```
```{r}
 p5 + theme_linedraw()

```
```{r}
 p5 + theme_minimal() +
    theme(text = element_text(color = "turquoise")) #overriding theme defaults
```
```{r}
 theme_new <- theme_bw() +
    theme(plot.background = element_rect(size = 1, color = "blue", fill = "black"),
          text=element_text(size = 12, family = "Serif", color = "ivory"),
          axis.text.y = element_text(colour = "purple"),
          axis.text.x = element_text(colour = "red"),
          panel.background = element_rect(fill = "pink"),
          strip.background = element_rect(fill = muted("orange")))

  p5 + theme_new #creating and saving new themes
```
# The #1 FAQ
## Map Aesthetics to diff columns
```{r}
 library(tidyr)
  home.land.byyear <- gather(housing.byyear,
                             value = "value",
                             key = "type",
                             Home.Value, Land.Value)
  ggplot(home.land.byyear,
         aes(x=Date,
             y=value,
             color=type)) +
    geom_line()
```
# Putting it all together
```{r}
dat <- read.csv("dataSets/EconomistData.csv")

  pc1 <- ggplot(dat, aes(x = CPI, y = HDI, color = Region))
  pc1 + geom_point() #basic scatter plot
```
```{r}
  (pc2 <- pc1 +
     geom_smooth(aes(group = 1),
                 method = "lm",
                 formula = y ~ log(x),
                 se = FALSE,
                 color = "red")) +
     geom_point() #adding trendline
```
```{r}
 ## A look at all 25 symbols
  df2 <- data.frame(x = 1:5 , y = 1:25, z = 1:25)
  s <- ggplot(df2, aes(x = x, y = y))
  s + geom_point(aes(shape = z), size = 4) + scale_shape_identity()
  ## While all symbols have a foreground colour, symbols 19-25 also take a
  ## background colour (fill)
  s + geom_point(aes(shape = z), size = 4, colour = "Red") +
    scale_shape_identity()
  s + geom_point(aes(shape = z), size = 4, colour = "Red", fill = "Black") +
    scale_shape_identity() #using open points
```
```{r}
#shape 1 open circle, so:
pc2 +
    geom_point(shape = 1, size = 4) 
```
```{r}
 (pc3 <- pc2 +
     geom_point(size = 4.5, shape = 1) +
     geom_point(size = 4, shape = 1) +
     geom_point(size = 3.5, shape = 1)) #multiple point layers of diff sizes
```
```{r}
#LABELING POINTS
 pointsToLabel <- c("Russia", "Venezuela", "Iraq", "Myanmar", "Sudan",
                     "Afghanistan", "Congo", "Greece", "Argentina", "Brazil",
                     "India", "Italy", "China", "South Africa", "Spane",
                     "Botswana", "Cape Verde", "Bhutan", "Rwanda", "France",
                     "United States", "Germany", "Britain", "Barbados", "Norway", "Japan",
                     "New Zealand", "Singapore") #identify points
```
```{r}
(pc4 <- pc3 +
    geom_text(aes(label = Country),
              color = "gray20",
              data = subset(dat, Country %in% pointsToLabel))) #label
```
```{r}
 library("ggrepel")
  pc3 +
    geom_text_repel(aes(label = Country),
              color = "gray20",
              data = subset(dat, Country %in% pointsToLabel),
              force = 10) #fix overlapping
```
```{r}
dat$Region <- factor(dat$Region,
                       levels = c("EU W. Europe",
                                  "Americas",
                                  "Asia Pacific",
                                  "East EU Cemt Asia",
                                  "MENA",
                                  "SSA"),
                       labels = c("OECD",
                                  "Americas",
                                  "Asia &\nOceania",
                                  "Central &\nEastern Europe",
                                  "Middle East &\nnorth Africa",
                                  "Sub-Saharan\nAfrica")) #change region labels and order
```
```{r}
pc4$data <- dat
  pc4
```
```{r}
#Add title and format axes
library(grid)
  (pc5 <- pc4 +
    scale_x_continuous(name = "Corruption Perceptions Index, 2011 (10=least corrupt)",
                       limits = c(.9, 10.5),
                       breaks = 1:10) +
    scale_y_continuous(name = "Human Development Index, 2011 (1=Best)",
                       limits = c(0.2, 1.0),
                       breaks = seq(0.2, 1.0, by = 0.1)) +
    scale_color_manual(name = "",
                       values = c("#24576D",
                                  "#099DD7",
                                  "#28AADC",
                                  "#248E84",
                                  "#F2583F",
                                  "#96503F")) +
    ggtitle("Corruption and Human development"))
```
```{r}
 library(grid) # for the 'unit' function
  (pc6 <- pc5 +
    theme_minimal() + # start with a minimal theme and add what we need
    theme(text = element_text(color = "gray20"),
          legend.position = c("top"), # position the legend in the upper left 
          legend.direction = "horizontal",
          legend.justification = 0.1, # anchor point for legend.position.
          legend.text = element_text(size = 11, color = "gray10"),
          axis.text = element_text(face = "italic"),
          axis.title.x = element_text(vjust = -1), # move title away from axis
          axis.title.y = element_text(vjust = 2), # move away for axis
          axis.ticks.y = element_blank(), # element_blank() is how we remove elements
          axis.line = element_line(color = "gray40", size = 0.5),
          axis.line.y = element_blank(),
          panel.grid.major = element_line(color = "gray50", size = 0.5),
          panel.grid.major.x = element_blank()
          )) #theme tweeks, see what diff themes do by changing and observing results
```
```{r}
library(grid)
png(file = "images/econScatter10.png", width = 800, height = 600)
pc6 
grid.text("Sources: Transparency International; UN Human Development Report",
x = .02, y = .03,
just = "left",
draw = TRUE)
grid.segments(x0 = 0.81, x1 = 0.825
              y0 = 0.90, y1 = 0.90,
                gp = gpar(col = "red"),
                draw = TRUE)
  grid.text(paste0("R² = ",
                   as.integer(mR2*100),
                   "%"),
            x = 0.835, y = 0.90,
            gp = gpar(col = "gray20"),
            draw = TRUE,
            just = "left")

  dev.off() #final version
```
